Added validation function for OS type

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -12,13 +12,24 @@ validate_host() {
 validate_int() {
     int=$1
     if (( ! $int > 0 )); then
-        echo "Error: INTERVAL ${int} must be a positive number like 1 or 35"
+        echo "Error: INTERVAL \"${int}\" must be a positive number like 1 or 35"
         exit 1
     fi
 }
 
+validate_os() {
+    os=$1
+    case "$os" in
+        os|core)
+            ;;
+        *)
+            echo "Error: OS \"${os}\" needs to be either unset or 'core' for Ubuntu Core or 'desktop' for Ubuntu Desktop"
+            exit 1
+    esac
+}
+
 validate_host "$(snapctl get host)"
 validate_int "$(snapctl get interval)"
-
+validate_os "$(snapctl get os)"
 
 snapctl restart "$SNAP_NAME"
